# UW Madison Courses: An Exploratory Analysis on worst grades

## Points Covered in the Analysis

1) What are the Worst Grades.

2) In which subjects students struggling.

3) Help them to select professor for tough courses.

4) Analyze the effect of number of classes in a week on studentâ€™s grades.

5) Analyze the effect of week day for the classes.

6) Warn student by flagging professors with strict grading.

In [2]:
import pandas as pd

In [7]:
path = r'C:\Users\mohit\Desktop\uw-madison-courses'
course_offerings = pd.read_csv(path+r'/course_offerings.csv')
courses = pd.read_csv(path+'/courses.csv')
grade_distributions = pd.read_csv(path+'/grade_distributions.csv')
instructors = pd.read_csv(path+'/instructors.csv')
rooms = pd.read_csv(path+'/rooms.csv')
schedules = pd.read_csv(path+'/schedules.csv')
sections = pd.read_csv(path+'/sections.csv')
subject_memberships = pd.read_csv(path+'/subject_memberships.csv')
subjects = pd.read_csv(path+'/subjects.csv')
teachings = pd.read_csv(path+'/teachings.csv')

In [16]:
df = [course_offerings,courses,grade_distributions,instructors,rooms,
     schedules,sections,subject_memberships,subjects,teachings]
for i in df:
    print(i.columns)

Index(['uuid', 'course_uuid', 'term_code', 'name'], dtype='object')
Index(['uuid', 'name', 'number'], dtype='object')
Index(['course_offering_uuid', 'section_number', 'a_count', 'ab_count',
       'b_count', 'bc_count', 'c_count', 'd_count', 'f_count', 's_count',
       'u_count', 'cr_count', 'n_count', 'p_count', 'i_count', 'nw_count',
       'nr_count', 'other_count'],
      dtype='object')
Index(['id', 'name'], dtype='object')
Index(['uuid', 'facility_code', 'room_code'], dtype='object')
Index(['uuid', 'start_time', 'end_time', 'mon', 'tues', 'wed', 'thurs', 'fri',
       'sat', 'sun'],
      dtype='object')
Index(['uuid', 'course_offering_uuid', 'section_type', 'number', 'room_uuid',
       'schedule_uuid'],
      dtype='object')
Index(['subject_code', 'course_offering_uuid'], dtype='object')
Index(['code', 'name', 'abbreviation'], dtype='object')
Index(['instructor_id', 'section_uuid'], dtype='object')

In [ ]:
def grade_avg(worst_results):
    worst_results['total_count'] = worst_results[['a_count', 'ab_count',
           'b_count', 'bc_count', 'c_count', 'd_count', 'f_count']].sum(axis = 1)
    worst_results['a_count'] = worst_results['a_count']/worst_results['total_count']
    worst_results['ab_count'] = worst_results['ab_count']/worst_results['total_count']
    worst_results['b_count'] = worst_results['b_count']/worst_results['total_count']
    worst_results['bc_count'] = worst_results['bc_count']/worst_results['total_count']
    worst_results['d_count'] = worst_results['d_count']/worst_results['total_count']
    worst_results['c_count'] = worst_results['c_count']/worst_results['total_count']
    worst_results['f_count'] = worst_results['f_count']/worst_results['total_count']
    return worst_results[worst_results['a_count'].notnull()]
test_rep = grade_avg(test_rep)

# Worst Grades
Let's start with finding out the worst grades and how it looks like. Where people are getting F and D's
For this Analysis we will only look at the class where there are more than 10 students in the class
we will look at the top 20 courses offering with worst grades.

Results: We can observe there is class with half of students got F and all are above 20% fail.

In [287]:
worst_results = grade_distributions[['course_offering_uuid', 'section_number', 'a_count', 'ab_count',
       'b_count', 'bc_count', 'c_count', 'd_count', 'f_count']].copy()
worst_results = grade_avg(worst_results)
worst_20 = worst_results[worst_results['total_count']>10].sort_values(['f_count','d_count',
                                                           'c_count','b_count'],ascending=False).head(20)
worst_20

,course_offering_uuid,section_number,a_count,ab_count,b_count,bc_count,c_count,d_count,f_count,total_count
3714,cd055dc8-5f49-3c89-92ac-0929d6a81084,4,0.083333,0.000000,0.000000,0.083333,0.333333,0.000000,0.500000,12
175477,a1c8ccd9-7cd8-31ec-b83d-67ba7fd7a5a7,2,0.038462,0.038462,0.269231,0.000000,0.269231,0.076923,0.307692,26
52594,34a20152-586a-3e22-80ab-7085dc732a05,1,0.129032,0.161290,0.096774,0.064516,0.129032,0.129032,0.290323,31
7788,06559b3c-af57-3b2c-932d-90fe9f6463d9,2,0.142857,0.071429,0.214286,0.000000,0.214286,0.071429,0.285714,14
3720,f0b6fb54-a960-3c2f-a57c-d102a4b6d802,4,0.166667,0.111111,0.166667,0.111111,0.055556,0.111111,0.277778,18
7720,256c5889-ad18-35f1-a9dc-b4fac2cbbedf,8,0.083333,0.083333,0.083333,0.166667,0.083333,0.250000,0.250000,12
7789,06559b3c-af57-3b2c-932d-90fe9f6463d9,3,0.062500,0.062500,0.187500,0.125000,0.187500,0.125000,0.250000,16
18302,76a77f62-8798-3f5e-b729-40df922b5bbd,16,0.333333,0.166667,0.083333,0.083333,0.083333,0.000000,0.250000,12
172990,01d5be82-2e2b-33c4-8d01-f6d6e3a7fbbd,15,0.166667,0.166667,0.333333,0.083333,0.000000,0.000000,0.250000,12
909,36754980-48d2-3b34-ad0c-d621a6cb30df,61,0.333333,0.250000,0.166667,0.000000,0.000000,0.000000,0.250000,12
52618,d88a4a0b-90c8-33ca-9b56-9a96012c7725,3,0.047619,0.142857,0.190476,0.095238,0.190476,0.095238,0.238095,21
7514,06233617-a4d4-3663-bba3-e050a9cd0643,2,0.142857,0.047619,0.095238,0.000000,0.428571,0.047619,0.238095,21
31871,dbad6e6a-a967-307d-99a9-b030166013c0,1,0.294118,0.117647,0.294118,0.058824,0.000000,0.000000,0.235294,17
192923,2bdf1519-7154-31b6-bc13-33bfd76c3b9f,1,0.352941,0.294118,0.117647,0.000000,0.000000,0.000000,0.235294,17
52615,059bd40a-f455-3b23-b640-b3561fd7de73,2,0.192308,0.115385,0.153846,0.115385,0.115385,0.076923,0.230769,26
3722,f0b6fb54-a960-3c2f-a57c-d102a4b6d802,6,0.000000,0.153846,0.384615,0.076923,0.076923,0.076923,0.230769,13
8847,999d0762-72d8-3061-ae24-1a23125fa1db,19,0.230769,0.384615,0.076923,0.076923,0.000000,0.000000,0.230769,13
3721,f0b6fb54-a960-3c2f-a57c-d102a4b6d802,5,0.000000,0.111111,0.166667,0.111111,0.277778,0.111111,0.222222,18
3712,cd055dc8-5f49-3c89-92ac-0929d6a81084,2,0.000000,0.043478,0.130435,0.086957,0.260870,0.260870,0.217391,23
7830,6150f2c1-384e-3786-88a4-8cb2f4aff03c,16,0.071429,0.000000,0.214286,0.000000,0.142857,0.357143,0.214286,14

## what are these subjects ??

Let's dig deep. We need to see that in which subjects students facing problem and getting bad grades.

In [288]:
# we need to remove these 2 entries.
subjects = subjects[~subjects['code'].isin(['ZZZ','SAB'])]
subjects['code'] = subjects['code'].astype('int')
worst_20 = worst_20.merge(subject_memberships, how = 'left',on = 'course_offering_uuid')
worst_20 = worst_20.merge(subjects, how = 'left',left_on= 'subject_code',right_on= 'code')
worst_20 = worst_20.drop(columns =['code','abbreviation'])
worst_20

,course_offering_uuid,section_number,a_count,ab_count,b_count,bc_count,c_count,d_count,f_count,total_count,subject_code,name
0,cd055dc8-5f49-3c89-92ac-0929d6a81084,4,0.083333,0.000000,0.000000,0.083333,0.333333,0.000000,0.500000,12,600,Mathematics
1,a1c8ccd9-7cd8-31ec-b83d-67ba7fd7a5a7,2,0.038462,0.038462,0.269231,0.000000,0.269231,0.076923,0.307692,26,600,Mathematics
2,34a20152-586a-3e22-80ab-7085dc732a05,1,0.129032,0.161290,0.096774,0.064516,0.129032,0.129032,0.290323,31,600,Mathematics
3,06559b3c-af57-3b2c-932d-90fe9f6463d9,2,0.142857,0.071429,0.214286,0.000000,0.214286,0.071429,0.285714,14,600,Mathematics
4,f0b6fb54-a960-3c2f-a57c-d102a4b6d802,4,0.166667,0.111111,0.166667,0.111111,0.055556,0.111111,0.277778,18,600,Mathematics
5,256c5889-ad18-35f1-a9dc-b4fac2cbbedf,8,0.083333,0.083333,0.083333,0.166667,0.083333,0.250000,0.250000,12,600,Mathematics
6,06559b3c-af57-3b2c-932d-90fe9f6463d9,3,0.062500,0.062500,0.187500,0.125000,0.187500,0.125000,0.250000,16,600,Mathematics
7,76a77f62-8798-3f5e-b729-40df922b5bbd,16,0.333333,0.166667,0.083333,0.083333,0.083333,0.000000,0.250000,12,600,Mathematics
8,01d5be82-2e2b-33c4-8d01-f6d6e3a7fbbd,15,0.166667,0.166667,0.333333,0.083333,0.000000,0.000000,0.250000,12,350,ENGLISH
9,36754980-48d2-3b34-ad0c-d621a6cb30df,61,0.333333,0.250000,0.166667,0.000000,0.000000,0.000000,0.250000,12,250,Communication Arts
10,d88a4a0b-90c8-33ca-9b56-9a96012c7725,3,0.047619,0.142857,0.190476,0.095238,0.190476,0.095238,0.238095,21,600,Mathematics
11,06233617-a4d4-3663-bba3-e050a9cd0643,2,0.142857,0.047619,0.095238,0.000000,0.428571,0.047619,0.238095,21,600,Mathematics
12,dbad6e6a-a967-307d-99a9-b030166013c0,1,0.294118,0.117647,0.294118,0.058824,0.000000,0.000000,0.235294,17,640,Atmospheric and Oceanic Sciences
13,2bdf1519-7154-31b6-bc13-33bfd76c3b9f,1,0.352941,0.294118,0.117647,0.000000,0.000000,0.000000,0.235294,17,420,Geoscience
14,2bdf1519-7154-31b6-bc13-33bfd76c3b9f,1,0.352941,0.294118,0.117647,0.000000,0.000000,0.000000,0.235294,17,778,Political Science
15,2bdf1519-7154-31b6-bc13-33bfd76c3b9f,1,0.352941,0.294118,0.117647,0.000000,0.000000,0.000000,0.235294,17,360,Environmental Studies - Gaylord Nelson Institute
16,059bd40a-f455-3b23-b640-b3561fd7de73,2,0.192308,0.115385,0.153846,0.115385,0.115385,0.076923,0.230769,26,600,Mathematics
17,f0b6fb54-a960-3c2f-a57c-d102a4b6d802,6,0.000000,0.153846,0.384615,0.076923,0.076923,0.076923,0.230769,13,600,Mathematics
18,999d0762-72d8-3061-ae24-1a23125fa1db,19,0.230769,0.384615,0.076923,0.076923,0.000000,0.000000,0.230769,13,351,English as a Second Language
19,f0b6fb54-a960-3c2f-a57c-d102a4b6d802,5,0.000000,0.111111,0.166667,0.111111,0.277778,0.111111,0.222222,18,600,Mathematics
20,cd055dc8-5f49-3c89-92ac-0929d6a81084,2,0.000000,0.043478,0.130435,0.086957,0.260870,0.260870,0.217391,23,600,Mathematics
21,6150f2c1-384e-3786-88a4-8cb2f4aff03c,16,0.071429,0.000000,0.214286,0.000000,0.142857,0.357143,0.214286,14,600,Mathematics

## MATH MATH MATH

I had the feeling. We can clearly observe most of the courses with bad grades are Math.

Solution: 
1) University should apply some prerequisites for Math course.

2) We can warn students about the past results.

3) we can provide the list of professors who are strict or lenient and then they can choose accordingly

## Below is the list of Math professor from strict to lenient and their grades distribution.

In [293]:
combine1 = worst_20.merge(sections, on = 'course_offering_uuid')
combine2 = combine1.merge(teachings,how = 'left', left_on='uuid',right_on='section_uuid')
combine2 = combine2.drop(columns = ['section_uuid'])
combine3 = combine2.merge(instructors,how = 'left', left_on='instructor_id',right_on='id')
combine3_math = combine3[combine3['name_x'] == 'Mathematics']
combine3.head(3)

,course_offering_uuid,section_number,a_count,ab_count,b_count,bc_count,c_count,d_count,f_count,total_count,subject_code,name_x,uuid,section_type,number,room_uuid,schedule_uuid,instructor_id,id,name_y
0,cd055dc8-5f49-3c89-92ac-0929d6a81084,4,0.083333,0.0,0.0,0.083333,0.333333,0.0,0.5,12,600,Mathematics,5694192b-8aa9-378d-88f6-52187b7ea011,LEC,6,7df5c6cc-71be-3843-b643-62f3c3b0fa7d,8d3f5c74-e7b8-394f-a3e7-5fc02f866ed9,3439400,3439400,MEHMET HALUK SENGUN
1,cd055dc8-5f49-3c89-92ac-0929d6a81084,4,0.083333,0.0,0.0,0.083333,0.333333,0.0,0.5,12,600,Mathematics,0f8c393b-14a5-3848-a67e-0041f95cf02f,LEC,4,7df5c6cc-71be-3843-b643-62f3c3b0fa7d,b8f8227d-d5bb-35a8-b903-d3213ede8a00,3633324,3633324,HOLLY CHEN
2,cd055dc8-5f49-3c89-92ac-0929d6a81084,4,0.083333,0.0,0.0,0.083333,0.333333,0.0,0.5,12,600,Mathematics,f8a7c187-d672-3ca9-ad74-a633c1227f64,LEC,5,b5dd07ca-e110-3822-8f92-e58b78b8126a,f22e3d99-0a1c-3659-8862-ca42da0e621a,3615589,3615589,ALI GODJALI

In [137]:
math_prof_score = pd.DataFrame(combine3_math.groupby(by = ['name_y']).agg({'a_count':'mean',
'ab_count':'mean',
'b_count':'mean',
'bc_count':'mean',
'c_count':'mean',
'd_count':'mean',
'f_count':'mean',
'total_count':'mean','name_y':'count'}).sort_values(['f_count',
                                                     'd_count',
                                                           'c_count','b_count'],
                                                    ascending=False))
math_prof_score = math_prof_score.rename(columns = {'name_y':'total_classes'})
math_prof_score.style.format({'a_count':"{:.2%}",
                              'ab_count':"{:.2%}",
                              'b_count':"{:.2%}",
                             'bc_count':"{:.2%}",
                             'c_count':"{:.2%}",
                             'd_count':"{:.2%}",
                             'f_count':"{:.2%}"})

### Select your professor carefully !!
# Effect of number of classes in a week

Here we are checking that is there any effect on grade of student based on how many classes scheduled for each subject within a week. For example: Math class: is twice a week, English class: Once a week (just an example, may not be true). So, we want to see there is any changes in grades if one class held 7 days a week as compare to 1 day a week.

### Steps:

1) merge schedule data with section to get tge course offering id.

2) merge the new data to grade dataset to get the grades.

3) filter the dataset where there is no class in whole week.

4) Group by number of class to see the impact on grades

In [277]:
schedule_merge = schedules.merge(sections[['course_offering_uuid','schedule_uuid']], how = 'left',left_on='uuid',right_on= 'schedule_uuid')
grade_merge = grade_distributions[['course_offering_uuid', 'section_number', 'a_count', 'ab_count',
       'b_count', 'bc_count', 'c_count', 'd_count', 'f_count']].copy()

In [278]:
test = schedule_merge.merge(grade_merge, how = 'left', on = 'course_offering_uuid')
#remove all the classes which are not scheduled 
test = test[~
((test['tues'] == False) &
(test['sun'] == False) &
(test['mon'] == False) &
(test['wed'] == False) &
(test['thurs'] == False) &
(test['fri'] == False) &
(test['sat'] == False)) ]
print(test.shape)

(812219, 20)

In [281]:
test_rep = test.replace({True:1,False:0})
test_rep['no_cls'] = test_rep['mon'] +test['tues']+test['sun']+test['wed']+test['thurs']+test['fri']+test['sat']
test_rep = grade_avg(test_rep)

In [284]:
# no significant results to say no of classes affect the grades
test_rep.groupby(by = test_rep['no_cls']).agg({'a_count':'mean',
'ab_count':'mean',
'b_count':'mean',
'bc_count':'mean',
'c_count':'mean',
'd_count':'mean',
'f_count':'mean',
'uuid':'count'})

,a_count,ab_count,b_count,bc_count,c_count,d_count,f_count,uuid
no_cls,,,,,,,,
1,0.476028,0.179319,0.197520,0.061622,0.061042,0.015371,0.009098,288168
2,0.360717,0.215745,0.243265,0.088752,0.066912,0.016133,0.008476,249253
3,0.379568,0.301413,0.199774,0.053307,0.044437,0.011644,0.009859,120551
4,0.329151,0.254270,0.269451,0.060292,0.063305,0.014335,0.009197,28336
5,0.505153,0.158326,0.202138,0.048145,0.061640,0.014302,0.010295,13856
6,0.449564,0.315271,0.224005,0.008551,0.002422,0.000000,0.000187,7009
7,0.237719,0.280955,0.467364,0.012645,0.000000,0.000000,0.001317,67

As number of classes does not have significant effect on the grades we will see if classes or days i.e. Monday, Friday, Sunday affects the grades.
For example: class grade on Monday vs Sunday or weekday vs weekend.

For that purpose, we are only considering the classes which held only once a week. One can dig deep by comparing all the possible ways.

# Effect of Week Day on grades.

Analyze the class grade based on the day class scheduled.

### Steps:
1) Filter the classes which only held once a week.

2) Group by according the weekday and average the grades to analyze the effects.

In [285]:
days_affect = test_rep[test_rep['no_cls']==1].copy()
x = days_affect[['mon','tues','wed','thurs','fri','sat','sun']].idxmax(axis = 1)
days_affect['day'] =x
days_affect = days_affect[days_affect['a_count'].notnull()]
days_affect_grop = days_affect.groupby(by = days_affect['day']).agg({'a_count':'mean',
'ab_count':'mean',
'b_count':'mean',
'bc_count':'mean',
'c_count':'mean',
'd_count':'mean',
'f_count':'mean',
'uuid':'count'})
days_affect_grop

,a_count,ab_count,b_count,bc_count,c_count,d_count,f_count,uuid
day,,,,,,,,
fri,0.377338,0.206161,0.223197,0.088392,0.076263,0.019447,0.009202,37728
mon,0.520472,0.169446,0.183497,0.050758,0.054227,0.013627,0.007973,52862
sat,0.759181,0.181790,0.046524,0.008636,0.002597,0.000383,0.000890,3352
sun,0.948185,0.028752,0.014644,0.002270,0.003133,0.002495,0.000521,198
thurs,0.445049,0.189744,0.211951,0.065857,0.063170,0.015402,0.008828,55636
tues,0.473821,0.173196,0.204407,0.059196,0.063129,0.016169,0.010082,69752
wed,0.508207,0.170255,0.183412,0.057066,0.057101,0.014408,0.009551,68640

## Weekend classes are the best!

#### On sunday 94% scored A, Saturday 75% scored A where as on Friday only 37% scored A :( 
We have observed that the average grades of classes which held on Weekends have significantly higher number of A's whereas classes on the Friday(last working day) have really low A grade. Sometimes, I also don't feel like working on Fridays!

# Strict Instructor
We can help students by flagging each professor according their grading pattern. It will give students a preview of how strict a professor grades and then they can decide which course they want to take. Sometimes in universities there will be multiple professors teaching the same course, so this might students to select whose classes they want to take.

### steps:
1) Merge the grading dataset to section instructor to get the unique id for each instructor.

2) Merge new dataset with the instructorâ€™s dataset to get the name. (you do not need to this step if you don't want to the names)

3) calculate the % of people for each grade.

4) At last average the grades by individual processor to identify how strict is the checking.

5) Sort it by Fail, D grade and so on.

In [273]:
Grade_section = grade_distributions.merge(sections, how = 'left',on = 'course_offering_uuid')
grade_prof = Grade_section.merge(teachings, how = 'left',left_on = 'uuid', right_on = 'section_uuid')
strict_instructor = grade_prof[['course_offering_uuid','a_count', 'ab_count',
       'b_count', 'bc_count', 'c_count', 'd_count', 'f_count', 'instructor_id']].copy()
strict_instructor = grade_avg(strict_instructor)

In [274]:
strict_instructor = strict_instructor.merge(instructors,how = 'left', left_on='instructor_id',right_on= 'id')
strict_instructor.columns

Index(['course_offering_uuid', 'a_count', 'ab_count', 'b_count', 'bc_count',
       'c_count', 'd_count', 'f_count', 'instructor_id', 'total_count', 'id',
       'name'],
      dtype='object')

In [275]:
strict_instructor = strict_instructor.groupby(by = strict_instructor['name']).agg({'a_count':'mean',
'ab_count':'mean',
'b_count':'mean',
'bc_count':'mean',
'c_count':'mean',
'd_count':'mean',
'f_count':'mean',
'course_offering_uuid':'count'}).sort_values(['f_count','d_count',
                                                           'c_count','b_count'],ascending=False)

### Top 10 strict instructor

In [276]:
strict_instructor[strict_instructor['course_offering_uuid'] >5].head(10)

,a_count,ab_count,b_count,bc_count,c_count,d_count,f_count,course_offering_uuid
name,,,,,,,,
JENNIFER LOSAW,0.147917,0.139761,0.216880,0.072080,0.132265,0.151941,0.139156,6
ALI GODJALI,0.166166,0.084674,0.213846,0.114901,0.176952,0.146580,0.096880,75
MASON DELANG,0.198260,0.064958,0.226213,0.058699,0.223364,0.136283,0.092223,25
MARKO BUDISIC,0.273472,0.147190,0.162204,0.125168,0.152202,0.049179,0.090585,6
HOLLY CHEN,0.224005,0.103552,0.212708,0.096311,0.185975,0.089009,0.088441,36
JACK JR. CARSON,0.221279,0.106970,0.230584,0.131302,0.187152,0.039566,0.083147,6
LONGQING WU,0.176490,0.106602,0.231013,0.098379,0.197937,0.106493,0.083084,28
STEVEN BAUMAN,0.192584,0.116294,0.161604,0.132138,0.193851,0.123730,0.079800,12
GARRETT ALSTON,0.198466,0.069731,0.256707,0.066673,0.217079,0.113749,0.077595,128
EMILY BAGUHN,0.250430,0.054742,0.300697,0.029031,0.186071,0.103815,0.075214,46